name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # Usando o token de autenticação

      - name: Set up Git config
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"

      - name: Debug Node.js and npm
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Debug Git
        run: |
          git status
          git log --oneline -n 5

      - name: Debugging info
        run: |
          echo "Checking Git status..."
          git status
          echo "Listing files in the repository..."
          ls -la

